spring:
  application:
    name: multicurrency
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Microservices@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: mysql

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
server:
  port: 8082
